server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
# automatically configures routes, but the request has to include the service name.
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

      routes[0]:
        id: EMPLOYEE-SERVICE
        uri: lb://EMPLOYEE-SERVICE # could also use hard coded url instead of the load balancing (lb) url
        predicates[0]: Path=/api/employees/**
      routes[1]:
        id: DEPARTMENT-SERVICE
        uri: lb://DEPARTMENT-SERVICE # could also use hard coded url instead of the load balancing (lb) url
        predicates[0]: Path=/api/departments/**

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.web: DEBUG
  pattern:
    level:
      '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'

# enable logging to see how the routes were mapped
#logging:
#  level:
#    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: debug
