spring:
  application:
    name: DEPARTMENT-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.web: DEBUG
  pattern:
    level:
      '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'

#  datasource:
#    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5444}/${POSTGRES_DB:udemy_1}
#    username: ${POSTGRES_USERNAME:udemy_1}
#    password: ${POSTGRES_PASSWORD:udemy_1}
#    driver-class-name: org.postgresql.Driver
#    connectionProperties:
#      sslFactory: org.postgresql.ssl.DefaultJavaSSLFactory
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#
#eureka:
#  instance:
#    client:
#      serverUrl:
#        defaultZone: http://localhost:8761/eureka